REQUEST_INTERVAL_MS: 1500
FIIS: "AAZQ11,ALZR11,BIDB11,BRCR11,BTHF11,BTLG11,CNES11,GAME11,HFOF11,HGLG11,JGPX11,RBRF11,RBRR11,RCRB11,RZAG11,URPR11,VCRA11,VGHF11,VGIA11,VGRI11,VRTA11,XPLG11"
#FIIS: "AAZQ11,ALZR11,BIDB11"
STOCKS: "CPLE6,ITSA4,PETR4,TAEE11,VALE3"
STATUS_INVEST.HOST: "https://statusinvest.com.br"
FIIS.HOST: "https://fiis.com.br"
SCRAPPER.ORIGIN: "status-invest"
