version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -DskipTests clean package
      - run:
          name: Test
          command: mvn clean test

workflows:
  default-workflow:
    jobs:
      - build-and-test